"""LookML Code Generator & AST Validator using lkml AST serialization."""

from pathlib import Path
from typing import Any, Dict, List, Optional
import lkml
import lkml.keys
import lkml.simple

from looker_kc_sync.mapping.transformers import title_case
from looker_kc_sync.models.lookml import (
    LookMLDimension,
    LookMLDimensionGroup,
    LookMLMeasure,
    LookMLView,
)

# Patch lkml keys to ensure 'synonyms' values are always quoted in lists
if "synonyms" not in lkml.keys.QUOTED_LITERAL_KEYS:
    lkml.keys.QUOTED_LITERAL_KEYS = lkml.keys.QUOTED_LITERAL_KEYS + ("synonyms",)
if "synonyms" not in lkml.simple.QUOTED_LITERAL_KEYS:
    lkml.simple.QUOTED_LITERAL_KEYS = lkml.simple.QUOTED_LITERAL_KEYS + ("synonyms",)


def _dimension_to_dict(dim: LookMLDimension, fields_hidden_by_default: bool = False) -> Dict[str, Any]:
    d: Dict[str, Any] = {
        "name": dim.name,
        "type": dim.type,
        "sql": dim.sql,
    }
    if dim.primary_key:
        d["primary_key"] = "yes"
    if fields_hidden_by_default:
        if not dim.hidden:
            d["hidden"] = "no"
    else:
        if dim.hidden:
            d["hidden"] = "yes"

    if not dim.hidden:
        if dim.label:
            d["label"] = dim.label
        if dim.description:
            d["description"] = dim.description
        if dim.synonyms:
            d["synonyms"] = dim.synonyms
        if dim.tags:
            d["tags"] = dim.tags
        if dim.suggestions:
            d["suggestions"] = dim.suggestions
        if dim.value_format_name:
            d["value_format_name"] = dim.value_format_name
        if dim.group_label:
            d["group_label"] = dim.group_label
    return d


def _dimension_group_to_dict(dg: LookMLDimensionGroup, fields_hidden_by_default: bool = False) -> Dict[str, Any]:
    d: Dict[str, Any] = {
        "name": dg.name,
        "type": dg.type,
        "sql": dg.sql,
    }
    if dg.timeframes:
        d["timeframes"] = dg.timeframes
    if dg.datatype:
        d["datatype"] = dg.datatype
    if fields_hidden_by_default:
        if not dg.hidden:
            d["hidden"] = "no"
    else:
        if dg.hidden:
            d["hidden"] = "yes"

    if not dg.hidden:
        if dg.label:
            d["label"] = dg.label
        if dg.description:
            d["description"] = dg.description
        if dg.synonyms:
            d["synonyms"] = dg.synonyms
        if dg.tags:
            d["tags"] = dg.tags
        if dg.group_label:
            d["group_label"] = dg.group_label
    return d


def _measure_to_dict(m: LookMLMeasure, fields_hidden_by_default: bool = False) -> Dict[str, Any]:
    d: Dict[str, Any] = {
        "name": m.name,
        "type": m.type,
        "sql": m.sql,
    }
    if fields_hidden_by_default:
        if not m.hidden:
            d["hidden"] = "no"
    else:
        if m.hidden:
            d["hidden"] = "yes"

    if not m.hidden:
        if m.label:
            d["label"] = m.label
        if m.description:
            d["description"] = m.description
        if m.synonyms:
            d["synonyms"] = m.synonyms
        if m.tags:
            d["tags"] = m.tags
        if m.value_format_name:
            d["value_format_name"] = m.value_format_name
        if m.group_label:
            d["group_label"] = m.group_label
    return d


def _view_to_dict(view: LookMLView) -> Dict[str, Any]:
    v: Dict[str, Any] = {
        "name": view.view_name,
        "sql_table_name": view.sql_table_name,
    }
    if view.fields_hidden_by_default:
        v["fields_hidden_by_default"] = "yes"
    if view.dimensions:
        v["dimensions"] = [_dimension_to_dict(d, view.fields_hidden_by_default) for d in view.dimensions]
    if view.dimension_groups:
        v["dimension_groups"] = [_dimension_group_to_dict(dg, view.fields_hidden_by_default) for dg in view.dimension_groups]
    if view.measures:
        v["measures"] = [_measure_to_dict(m, view.fields_hidden_by_default) for m in view.measures]
    return v


class LookMLGenerator:
    """Renders normalized LookML models into valid LookML files and validates with lkml AST parser."""

    def __init__(self, template_dir: Optional[Path] = None):
        self.template_dir = template_dir

    def render_base_view(self, view: LookMLView) -> str:
        """Renders a base view file via AST serialization and validates it with lkml."""
        view_dict = _view_to_dict(view)
        body = lkml.dump({"views": [view_dict]})

        header_lines = [
            "# AUTO-GENERATED BY KC-LOOKER-SYNC. DO NOT EDIT DIRECTLY.",
        ]
        if view.source_entry:
            header_lines.append(f"# Source Entry: {view.source_entry}")
        if view.description:
            for desc_line in view.description.strip().splitlines():
                header_lines.append(f"# Description: {desc_line}")

        rendered = "\n".join(header_lines) + "\n\n" + body

        # Validate with lkml AST parser
        try:
            lkml.load(rendered)
        except Exception as e:
            raise ValueError(f"Generated LookML for view {view.base_view_name} failed lkml validation: {e}")

        return rendered

    def render_curated_refinement(self, view: LookMLView) -> str:
        """Renders a starter curated refinement view."""
        rendered = (
            f"# HUMAN CURATED REFINEMENT LAYER\n"
            f"# Refines machine-generated base view without modifying base files directly.\n"
            f'include: "/views/base/{view.view_name}.base.view.lkml"\n\n'
            f"view: +{view.view_name} {{\n"
            f"  # Add human-curated measures, composite metrics, and drill paths below\n"
            f"}}\n"
        )
        try:
            lkml.load(rendered)
        except Exception as e:
            raise ValueError(f"Generated LookML refinement for {view.base_view_name} failed validation: {e}")
        return rendered

    def render_model(self, model_name: str, connection_name: str, views: List[LookMLView]) -> str:
        """Renders the LookML model file with starter explores for each view."""
        explores_lkml = []
        for v in views:
            label = title_case(v.view_name)
            desc = v.description or f"Explore for {label}"
            explores_lkml.append(
                f"explore: {v.view_name} {{\n"
                f'  label: "{label}"\n'
                f'  description: "{desc}"\n'
                f"}}"
            )

        rendered = (
            f"# LookML Model Definition\n"
            f'connection: "{connection_name}"\n\n'
            f'include: "/views/curated/*.view.lkml"\n\n'
            f"# Explores\n" + "\n\n".join(explores_lkml) + "\n"
        )
        try:
            lkml.load(rendered)
        except Exception as e:
            raise ValueError(f"Generated model {model_name} failed validation: {e}")
        return rendered
